### ISSUE TITLE
Data source broken link 

### ISSUE THREAD

**Issue by MjdMahasneh** [jelifysh/U-NET-Segmentation-with-Keras#1]
Could you kindly add some info on how to acquire data (and maybe a few words to describe data, such as, source, type, label production, and data format)? The link provided does not work.

That would be really helpful for re-production/re-purposing.

Many thanks in advance.

**Comment by tanishqgautam** [comment]
The datasets come from Shenzhen and Montgomery respectively.
1. China Set - The Shenzhen set :- Number of X-rays:
336 cases with manifestation of tuberculosis, and
326 normal cases.

2. Montgomery County X-ray Set:- This set contains 138 posterior-anterior x-rays, of which 80 x-rays are normal and 58 x-rays are abnormal with manifestations of tuberculosis.

You can use the official link :- https://lhncbc.nlm.nih.gov/publication/pub9931 to download both the datasets.

**Comment by MjdMahasneh** [comment]
That is awesome, thank you for the elaboration and the prompt response.

**Comment by MjdMahasneh** [comment]
@jelifysh Have you used both datasets for training and testing? Also am curious to know, was there any pre-processing used to unify the two datasets (e.g. unifying resolution, and/or unifying/normalizing range of values in both datasets)

Lastly, and most importantly, in the implementation you're providing, the visualizations seem to correspond to a CT scan rather X-Ray (Kindly correct me if am wrong). After inspecting the datasets, I noticed the visualized images in your example look completely different, could you please assist me to understand why is this the case?

I would very much appreciate any clarification.
Many thanks.

**Comment by tanishqgautam** [comment]
Hi,

Sorry I had gotten confused with the dataset used. The correct dataset is [here](https://drive.google.com/drive/folders/11F3wGaclTnd7VatyGQNcKKkpTsyK4wtq?usp=sharing).

This dataset is a collection of 2D images with manually segmented lungs taken from the Kaggle Data Science Bowl 2017 challenge.

**Comment by MjdMahasneh** [comment]
That's awesome! thank you again for the help! it is a very nice, self-contained, and simple repo.
